{
    "name": "libnvfatbin",
    "ecosystem": "pypi",
    "campaign": "2025-10-bugdotexe",
    "affected_versions": [
        "2.3.2",
        "12.4.127"
    ],
    "campaign_assigned_at": "2025-10-29T22:04:14.173183+00:00",
    "campaign_data_modified_at": "2025-10-30T07:16:27.141229+00:00"
}